# Generated by Django 5.2.5 on 2025-08-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
